name: Build Go Binaries
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g., 0.1.0)'
        required: true
        default: '1.'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # No need to list individual architectures here, GoReleaser handles it
        # You can still use a matrix for other job-level settings if needed
        include:
          - job_name: goreleaser_build # Just a descriptive name for the job matrix
    name: ${{ matrix.job_name }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed by GoReleaser for git information

      # Use the GoReleaser Action for building
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser # Use the standard goreleaser distribution
          version: latest # Or a specific version like 'v1.24.0'
          args: build --clean --snapshot # Use the 'build' command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for some GoReleaser features, optional for just build


      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
